### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by miraydamartinez** [kadduz/Codecademy#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code included runs without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code produces the suite of functions and classes required of it and calls them in an appropriate order.

### Criteria 3: Software Architecture
* _Score Level:_4 (Exceeds Expectations)
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes. There is one instance (towards the end) where different functions are all together which was a little confusing because they should be in their respective sections. It'd be great to separate your functions in a future project to make it clearer that they are not the same. 
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code uses language features appropriately. If a task can be solved with a Python language feature, it is.

### Criteria 5: Produces Accurate Output
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code output is properly formatted and accurate.
 
### Overall Score: 20/20
Well done! You used your knowledge of Python to find out who the killer was (Can you believe it was Lily?) You showed a great understanding of project requirements and python language features and used them to your advantage. My only advice going forward (if you don't do this already), is to test your code incrementally. After adding a new variable, function, class, or anything really, it's important to test the output of your code and see if there is any error(s). This helps you in the long-run from having to find a small error from large sums of code!

**Comment by kadduz** [comment]
Thanks for the review and the advice, I will keep it in mind.
